# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('zip', models.IntegerField()),
                ('main_address', models.TextField()),
                ('main_city', models.TextField()),
                ('main_state', models.TextField()),
                ('main_zip', models.IntegerField()),
                ('main_phone', models.TextField()),
                ('main_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
