# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 05:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('main_address', models.TextField(blank=True, null=True)),
                ('main_city', models.TextField(blank=True, null=True)),
                ('main_state', models.TextField(blank=True, null=True)),
                ('main_zip', models.IntegerField(blank=True, null=True)),
                ('main_phone', models.TextField(blank=True, null=True)),
                ('main_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('geo_position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
