# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsource',
            name='dummy_email',
            field=models.EmailField(default='asjhdg@jhgasdf.rhg', max_length=254),
        ),
    ]
