# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsource',
            name='description_1',
        ),
    ]
