# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile_api', '0002_remove_foodsource_description_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('day_of_the_week', models.CharField(choices=[(b'Monday', b'Monday'), (b'Tuesday', b'Tuesday'), (b'Wednesday', b'Wednesday'), (b'Thursday', b'Thursday'), (b'Friday', b'Friday'), (b'Saturday', b'Saturday'), (b'Sunday', b'Sunday')], default=b'Monday', max_length=15)),
                ('food_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smile_api.FoodSource')),
            ],
        ),
    ]
