# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_api', '0002_foodsource_dummy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsource',
            name='dummy_email',
        ),
    ]
