# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 02:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_api', '0003_remove_foodsource_dummy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsource',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=(12.4604, 43.942), srid=4326),
        ),
    ]
