# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile_api', '0003_workinghours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghours',
            old_name='day_of_the_week',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='food_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='smile_api.FoodSource'),
        ),
    ]
