# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 02:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_api', '0004_foodsource_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsource',
            name='point',
        ),
        migrations.AddField(
            model_name='foodsource',
            name='geo_position',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='main_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='main_city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='main_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='main_phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='main_state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='main_zip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodsource',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
