# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_agent_ask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpreter',
            name='hoge',
        ),
    ]
