# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_agent_ask', '0002_remove_interpreter_hoge'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreter',
            name='hoge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
