# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_agent_ask', '0003_interpreter_hoge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpreter',
            old_name='hoge',
            new_name='locations',
        ),
        migrations.AddField(
            model_name='interpreter',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='protocol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='subservices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interpreter',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
